### ISSUE TITLE
Make me an issue!

### ISSUE THREAD

**Issue by testworksau** [addisonschultz/github-cards#67]
Imported from Miro

**Comment by addisonschultz** [comment]
Hey @testworksau! Very cool you're using / testing this integration - I've also seen your feedback on the GH app-examples repository, and definitely have plans to improve the overall experience of getting it up and running. 

I was curious to know about your use case a bit more about the app in general, and if you are interested in learning more about the ins and outs of how it's built? 

I'd love to hop on a call sometime to pick your brain on some of these things, so if you have some time in the coming days/weeks, feel free to reach out to me in our developer Discord! 

https://bit.ly/miro-developers

**Comment by testworksau** [comment]
Hi @addisonschultz - sorry for the spam, I had no idea an issue would be created in here!

Last Monday, we met with some Miro representatives - emma.l and ross.j at miro.com; we presented our use case, which led to the discovery of this example. We thought we'd play around with it in order to see if it's worth us building on, or waiting for.

Ultimately, we're looking to switch from Jira to GitHub issues, and are looking for equivalence (or better) in terms of the ability to create, update, and sync GitHub issues from within a Miro board.

Thanks for offering to get on a call - I wouldn't mind playing around with the example a bit more, before coming back to you with some more observations etc. (perhaps in a couple of weeks, via discord, if you're OK with that?)

**Comment by addisonschultz** [comment]
Hey @testworksau, absolutely! Feel free to ping me in our Discord at any time, or shoot me a message here. I've also had a quick sync with the Mironeers you were chatting with earlier, so they can also bring me up to speed on what you're looking for in terms of workflow/platform capabilities. 

Hope to chat soon! Let me know if you have anything for me in the meantime.
